# references:
# * http://www.objc.io/issue-6/travis-ci.html

language: objective-c
cache: bundler
osx_image: xcode8.3
xcode_workspace: ViaSwiftUtils.xcworkspace
xcode_scheme: ViaSwiftUtils_iOS

install:
  - ./install_swiftlint.sh
  - bundle install

script:
  - bundle exec danger
  - open -a "simulator" --args -CurrentDeviceUDID AB104968-7058-4AE2-A95D-DBB77634C642
  - set -o pipefail && xcodebuild test -workspace ViaSwiftUtils.xcworkspace -scheme ViaSwiftUtils_iOS -sdk iphonesimulator -destination "OS=10.3.1,name=iPhone 6s" | xcpretty
