# references:
# * http://www.objc.io/issue-6/travis-ci.html

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
      sudo: required
      language: objective-c
      env:
        matrix:
          - TEST_DESTINATION="OS=11.0,name=iPhone 7"
          - TEST_DESTINATION="OS=9.3,name=iPhone 6"

cache: bundler

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

install:
  - ./install_swiftlint.sh
  - bundle install
  
script:
  - bundle exec danger
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
